//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int commentId { get; set; }
        public string commentorName { get; set; }
        public string commentorMail { get; set; }
        public Nullable<bool> commentApprove { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
        public string commentContent { get; set; }
    }
}
