//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainer
    {
        public int trainerId { get; set; }
        public string trainerNameSurname { get; set; }
        public string area { get; set; }
        public string tel { get; set; }
    }
}
